-- MySQL Script generated by MySQL Workbench
-- 04/20/15 21:38:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wms` ;

-- -----------------------------------------------------
-- Schema wms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wms` DEFAULT CHARACTER SET gbk ;
SHOW WARNINGS;
USE `wms` ;

-- -----------------------------------------------------
-- Table `wms`.`commodity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`commodity` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wms`.`commodity` (
  `commodityId` INT(11) NOT NULL AUTO_INCREMENT,
  `commodityNum` VARCHAR(11) NOT NULL,
  `commodityBar` VARCHAR(11) NULL DEFAULT NULL,
  `commodityName` VARCHAR(50) NOT NULL,
  `commodityType` VARCHAR(20) NULL DEFAULT NULL,
  `remark` VARCHAR(255) NULL DEFAULT NULL,
  `commodityCategoryId` INT(11) NULL DEFAULT '0',
  `commodityUnit` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`commodityId`),
  UNIQUE INDEX `commodityId_UNIQUE` (`commodityNum` ASC),
  INDEX `fk_commodity_commodityCategory_idx` (`commodityCategoryId` ASC),
  INDEX `fk_commodity_unit_idx` (`commodityUnit` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = gbk;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wms`.`commoditycategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`commoditycategory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wms`.`commoditycategory` (
  `commodityCategoryId` INT(11) NOT NULL AUTO_INCREMENT,
  `commodityCategoryName` VARCHAR(50) NOT NULL,
  `pid` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`commodityCategoryId`),
  UNIQUE INDEX `commodityCategoryId_UNIQUE` (`commodityCategoryId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wms`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`unit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wms`.`unit` (
  `unitId` INT(11) NOT NULL AUTO_INCREMENT,
  `unitName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`unitId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = gbk;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wms`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wms`.`user` (
  `userid` INT(11) NOT NULL AUTO_INCREMENT,
  `loginname` VARCHAR(50) NOT NULL DEFAULT '',
  `password` VARCHAR(50) NOT NULL DEFAULT '',
  `username` VARCHAR(50) NOT NULL DEFAULT '',
  `age` INT(10) NULL DEFAULT NULL,
  `sex` VARCHAR(50) NULL DEFAULT NULL,
  `createDate` DATE NULL DEFAULT NULL,
  `lastUpdateDate` DATE NULL DEFAULT NULL,
  `disableDate` DATE NULL DEFAULT NULL,
  `usertype` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
