-- MySQL Script generated by MySQL Workbench
-- 04/23/15 16:54:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wms` ;

-- -----------------------------------------------------
-- Schema wms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wms` DEFAULT CHARACTER SET utf8 ;
USE `wms` ;

-- -----------------------------------------------------
-- Table `wms`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`client` ;

CREATE TABLE IF NOT EXISTS `wms`.`client` (
  `clientID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '客户ID',
  `clientName` VARCHAR(50) NOT NULL COMMENT '客户姓名',
  `contactPeople` VARCHAR(30) NULL DEFAULT NULL COMMENT '联系人',
  `contactNum` VARCHAR(30) NULL DEFAULT NULL COMMENT '联系电话',
  `address` VARCHAR(50) NULL DEFAULT NULL COMMENT '地址',
  `remark` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`clientID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '客户信息';


-- -----------------------------------------------------
-- Table `wms`.`commodity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`commodity` ;

CREATE TABLE IF NOT EXISTS `wms`.`commodity` (
  `commodityId` INT(11) NOT NULL AUTO_INCREMENT,
  `commodityName` VARCHAR(50) CHARACTER SET 'gbk' NOT NULL,
  `commodityType` VARCHAR(20) CHARACTER SET 'gbk' NULL DEFAULT NULL,
  `categoryId` INT(11) NULL DEFAULT '0',
  `unitId` INT(11) NULL DEFAULT '0',
  `purchasePrice` DOUBLE NULL DEFAULT NULL COMMENT '平均成本价',
  `salePrice` DOUBLE NULL DEFAULT NULL COMMENT '销售单价',
  `lastPrice` DOUBLE NULL DEFAULT NULL COMMENT '上次进价',
  `stockAmount` INT(11) NULL DEFAULT NULL COMMENT '库存数量',
  `minimum` INT(11) NULL DEFAULT NULL,
  `state` INT(11) NULL DEFAULT NULL,
  `remark` VARCHAR(255) CHARACTER SET 'gbk' NULL DEFAULT NULL,
  `coordinate` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`commodityId`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COMMENT = '商品信息';


-- -----------------------------------------------------
-- Table `wms`.`commoditycategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`commoditycategory` ;

CREATE TABLE IF NOT EXISTS `wms`.`commoditycategory` (
  `cid` INT(11) NOT NULL AUTO_INCREMENT COMMENT '商品分类ID',
  `cname` VARCHAR(50) NOT NULL COMMENT '商品分类名称',
  `pid` INT(11) NOT NULL DEFAULT '0' COMMENT '父ID',
  PRIMARY KEY (`cid`),
  UNIQUE INDEX `commodityCategoryId_UNIQUE` (`cid` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = '商品分类';


-- -----------------------------------------------------
-- Table `wms`.`purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`purchase` ;

CREATE TABLE IF NOT EXISTS `wms`.`purchase` (
  `purchaseId` VARCHAR(14) NOT NULL COMMENT '进货单ID',
  `supplierId` INT(11) NULL DEFAULT NULL COMMENT '供应商ID',
  `createDate` DATE NOT NULL COMMENT '表单创建日期',
  `payablePrice` DOUBLE NULL DEFAULT NULL COMMENT '应付金额',
  `realPrice` DOUBLE NULL DEFAULT NULL COMMENT '实付金额',
  `state` INT(11) NULL DEFAULT NULL COMMENT '进货单状态',
  `userId` INT(11) NULL DEFAULT NULL COMMENT '操作员ID',
  `remark` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`purchaseId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COMMENT = '进货单';


-- -----------------------------------------------------
-- Table `wms`.`purchasegoods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`purchasegoods` ;

CREATE TABLE IF NOT EXISTS `wms`.`purchasegoods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '进货单商品信息ID',
  `purchaseId` VARCHAR(14) CHARACTER SET 'gbk' NOT NULL COMMENT '进货单ID',
  `commodityId` INT(11) NULL DEFAULT NULL COMMENT '商品ID',
  `price` DOUBLE NULL DEFAULT NULL COMMENT '进货单价',
  `amount` INT(11) NULL DEFAULT NULL COMMENT '总量',
  `totalPrice` DOUBLE NULL DEFAULT NULL COMMENT '总价',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '进货单商品信息';


-- -----------------------------------------------------
-- Table `wms`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`sale` ;

CREATE TABLE IF NOT EXISTS `wms`.`sale` (
  `saleId` VARCHAR(14) NOT NULL COMMENT '销售单ID',
  `clientId` INT(11) NULL DEFAULT NULL COMMENT '客户ID',
  `createDate` DATE NOT NULL COMMENT '创表日期',
  `payablePrice` DOUBLE NULL DEFAULT NULL COMMENT '应付金额',
  `realPrice` DOUBLE NULL DEFAULT NULL COMMENT '实付金额',
  `state` VARCHAR(2) NULL DEFAULT NULL COMMENT '订单状态',
  `userId` INT(11) NULL DEFAULT NULL COMMENT '操作员',
  `remark` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`saleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '销售出库';


-- -----------------------------------------------------
-- Table `wms`.`salegoods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`salegoods` ;

CREATE TABLE IF NOT EXISTS `wms`.`salegoods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '销售商品单ID',
  `saleId` VARCHAR(14) NOT NULL COMMENT '销售单ID',
  `commodityId` INT(11) NULL DEFAULT NULL COMMENT '商品ID',
  `price` DOUBLE NULL DEFAULT NULL COMMENT '单价',
  `amount` INT(11) NULL DEFAULT NULL COMMENT '总量',
  `totalPrice` DOUBLE NULL DEFAULT NULL COMMENT '总价',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '销售单商品信息';


-- -----------------------------------------------------
-- Table `wms`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`supplier` ;

CREATE TABLE IF NOT EXISTS `wms`.`supplier` (
  `supplierId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '供应商ID',
  `supplierName` VARCHAR(50) CHARACTER SET 'gbk' NOT NULL COMMENT '供应商姓名',
  `contactPeople` VARCHAR(30) CHARACTER SET 'gbk' NULL DEFAULT NULL COMMENT '联系人',
  `contactNum` VARCHAR(30) CHARACTER SET 'gbk' NULL DEFAULT NULL COMMENT '联系电话',
  `address` VARCHAR(50) CHARACTER SET 'gbk' NULL DEFAULT NULL COMMENT '联系地址',
  `remark` VARCHAR(200) CHARACTER SET 'gbk' NULL DEFAULT NULL COMMENT '备注',
  `contactTel` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`supplierId`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COMMENT = '供应商';


-- -----------------------------------------------------
-- Table `wms`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`unit` ;

CREATE TABLE IF NOT EXISTS `wms`.`unit` (
  `unitId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '计量单位ID',
  `unitName` VARCHAR(50) NOT NULL COMMENT '计量单位名称',
  PRIMARY KEY (`unitId`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COMMENT = '计量单位';


-- -----------------------------------------------------
-- Table `wms`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wms`.`user` ;

CREATE TABLE IF NOT EXISTS `wms`.`user` (
  `userid` INT(11) NOT NULL AUTO_INCREMENT,
  `loginname` VARCHAR(50) CHARACTER SET 'gbk' NOT NULL DEFAULT '',
  `password` VARCHAR(50) CHARACTER SET 'gbk' NOT NULL DEFAULT '',
  `username` VARCHAR(50) CHARACTER SET 'gbk' NOT NULL DEFAULT '',
  `age` INT(10) NULL DEFAULT NULL,
  `sex` VARCHAR(50) CHARACTER SET 'gbk' NULL DEFAULT NULL,
  `createDate` DATE NULL DEFAULT NULL,
  `lastUpdateDate` DATE NULL DEFAULT NULL,
  `disableDate` DATE NULL DEFAULT NULL,
  `usertype` VARCHAR(20) CHARACTER SET 'gbk' NULL DEFAULT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '用户信息';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
